# Generated by Django 3.2.16 on 2022-11-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0004_auto_20221101_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(through='cook.ingredient_recipe', to='cook.ingredients'),
        ),
    ]
