# Generated by Django 3.2.16 on 2022-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0005_alter_recipes_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(through='cook.ingredient_recipe', to='cook.ingredients'),
        ),
    ]
