# Generated by Django 3.2.9 on 2022-11-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0010_auto_20221106_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ingredient_recipe',
            new_name='IngredientRecipe',
        ),
    ]
