# Generated by Django 3.2.16 on 2022-10-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221029_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ACCESS_LEVEL',
            field=models.CharField(choices=[('guest', 'guest'), ('user', 'user'), ('admin', 'administrator')], default='guest', max_length=50, null=True, verbose_name='Уровень доступа'),
        ),
    ]
